// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Database;

#nullable disable

namespace TaskManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240713184846_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Models.Activity", b =>
                {
                    b.Property<int>("Act_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Act_Id"));

                    b.Property<DateTime>("Act_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Act_ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Act_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tasks_Id")
                        .HasColumnType("integer");

                    b.HasKey("Act_Id");

                    b.HasIndex("Tasks_Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TaskManagement.Models.Project", b =>
                {
                    b.Property<int>("Project_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Project_Id"));

                    b.Property<string>("Project_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Project_Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TaskManagement.Models.Tasks", b =>
                {
                    b.Property<int>("Tasks_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Tasks_Id"));

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Task_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Tasks_Id");

                    b.HasIndex("Project_Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskManagement.Models.Activity", b =>
                {
                    b.HasOne("TaskManagement.Models.Tasks", "Tasks")
                        .WithMany("Activities")
                        .HasForeignKey("Tasks_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagement.Models.Tasks", b =>
                {
                    b.HasOne("TaskManagement.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("Project_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagement.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagement.Models.Tasks", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
